[Interface]
PrivateKey = 6N/slwdo/f9NXZAs98OlKkdrRfyCmaPav+Ifv3QHkE8=
Address = 56.56.56.56/32
DNS = 6.6.6.6

[Peer]
PublicKey = EFQWTGSGSjifkjsecnqdkf;,kjzrtigkojvkoslerjgt(ç§àt"'à)0359036gjndfngjvksd=
AllowedIPs = 34.34.34.34/24
Endpoint = 92.103.155.15:51820
PersistentKeepalive = 25
