[Interface]
PrivateKey = 0CcO/iW+6QFmCr6GIU7FoLiQmDiJzHlhe+LszOzcpH4=
Address = 12.12.12.12/32
DNS = 1.1.1.1

[Peer]
PublicKey = WFROGEDCferflcfgk23454@@===++===
AllowedIPs = 7.7.7.7/24
Endpoint = 80.11.161.231:51820
PersistentKeepalive = 25
