[Interface]
PrivateKey = CPtIIEmtRC3eVqAL/5nZA/4vvISbJRW26jgfvFCWams=
Address = 45.45.45.54/32
DNS = 3.3.3.3

[Peer]
PublicKey = DJFhdsjhgizdcjOKIJDIRZKFC==
AllowedIPs = 8.8.8.8/24
Endpoint = 2.96.155.118:51820
PersistentKeepalive = 25
