[Interface]
PrivateKey = 4KwN4TGHHUOHfi2mEZd2BTEPenxxPaRZuRUDfAVCMkY=
Address = 1.1.1.1/32
DNS = 1.1.1.1

[Peer]
PublicKey = LDFFCFZE2123++=====
AllowedIPs = 12.12.12.12/24
Endpoint = 85.69.229.209:51542
PersistentKeepalive = 25
