[Interface]
PrivateKey = eC27GOOhW15OI04UqVWtZFHEoAn5LqiFxZDhlZbNY0Y=
Address = 123244314
DNS = 314534534

[Peer]
PublicKey = gJTzJfszmhb+IkoD7sYf/X0q3283HLeFFCMu4D3NUUk=
AllowedIPs = 34AT5RE4T5RF45
Endpoint = R4ZT5Y67HTRGAZ
PersistentKeepalive = 25