[Interface]
PrivateKey = QFF6HPEjSRAJMaSqHTDCAHgwhDNAvsw9VAhoT+ggdVY=
Address = 34.34.34.34/32
DNS = 6.6.6.6

[Peer]
PublicKey = FJVHUJFjdhufijf394°0230@@=
AllowedIPs = 2.2.2.2/24
Endpoint = 92.103.155.15:51820
PersistentKeepalive = 25
