[Interface]
PrivateKey = WNQnehf1AfYaiiihbpB07DdtR3o44zCrS8HRI66KUmw=
Address = 12.12.12.12/122
DNS = 1.1.1.1

[Peer]
PublicKey = rWsw5BfrSmKc1kIfycITH728y3twxaS0027SN8opFSs=
AllowedIPs = None
Endpoint = sdf.poik.lkj:12349
PersistentKeepalive = 12