[Interface]
PrivateKey = OHcYexPd8uUSQE3A+TjiMyXO7B38e4+LgXTBkjErikk=
Address = 1.1.1.1/14
DNS = 1.1.1.1

[Peer]
PublicKey = nomyHWnO8bkhdtSR5WpEUeM+w4X+RxhsivZPL3DEfTQ=
AllowedIPs = 10.10.10.3/24
Endpoint = kdj.odifj.eofke:12345
PersistentKeepalive = 25
