[Interface]
PrivateKey = AA96yMP1mUi3+RLIaxgSZO6BOg0/6gA9cN4oZo2RdUw=
Address = 1.1.1.1/24
DNS = 1.1.1.1

[Peer]
PublicKey = jdhvejfOIJIDOGJOEF=
AllowedIPs = 1.1.1.1/24
Endpoint = 1.1.1.1:234
PersistentKeepalive = 25
