[Interface]
PrivateKey = YJ2m6VUULqn54EhEUIW32bXL9iDXhT0aHIhIU28n9lA=
Address = 3.3.3.3/32
DNS = 3.3.3.3

[Peer]
PublicKey = JDHEGCJBHSDChbnerhcjzhe)аз!и@@=
AllowedIPs = 3.3.3.3/24
Endpoint = 12.12.12.12:345
PersistentKeepalive = 25
