[Interface]
PrivateKey = 4FXGsLnxgIZC39t4DavxoZAan93XwRCnpDQvjL7rM1E=
Address = 12.12.12.12/32
DNS = 5.5.5.5

[Peer]
PublicKey = JFJKSDNijeodsierjoke12342@@++===
AllowedIPs = 6.6.6.6/24
Endpoint = 23.23.232.3:234
PersistentKeepalive = 25
