[Interface]
PrivateKey = cN/x/Pr1jth5EkO7AmvGTCVqGhm4i6cTHjzA7ijXUW8=
Address = 10.10.10.2/32
DNS = 192.168.1.100

[Peer]
PublicKey = sJGVSzJUTxHlgt7aNKpDEFTB8cILwVLSYuwdgOPSUTw=
AllowedIPs = None
Endpoint =  92.103.155.15:51820
PersistentKeepalive = 25