[Interface]
PrivateKey = iPPNSXpdjs9YtTfmAVXLR7rclI48nSvRRyfzMFfpsk8=
Address = 10.10.10.10/24
DNS = 1.1.1.1

[Peer]
PublicKey = RtKjd4ZVqIiFsbn6x5XGp39d3gCiKzlWhgzpzmTyMGU=
AllowedIPs = None
Endpoint = 
PersistentKeepalive = 25
