[Interface]
PrivateKey = sL8kvPTGmKR4ReGVgSBU2x52c6WLLYPiabt+qZJSi18=
Address = 12.12.12.12/32
DNS = 1.1.1.1

[Peer]
PublicKey = RJFHjdjerjgbjrej03491JDjdfnjlldjffe==
AllowedIPs = 3.3.3.3/24
Endpoint = 45.80.24.211:51820
PersistentKeepalive = 25
