[Interface]
PrivateKey = 8JSkZT3NgeQvdd94UGPXK70cjMJkkgm6uJlGWjLULn0=
Address = 12.12.12.12/24
DNS = 1.1.1.1

[Peer]
PublicKey = LCJJkdjcnjefei234@@==__====
AllowedIPs = 12.12.12.12/32
Endpoint = 80.11.11.231:51820
PersistentKeepalive = 25
